<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Tests/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Motor/Motor.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageReference Include="NUnit" Version="*" />
    <PackageReference Include="NUnit3TestAdapter" Version="*" />
  </ItemGroup>
</Project>
